import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

import { useState } from "react";

export default function Home() {
  const [todos, settodos] = useState([]);

  const [newTodo, setnewTodo] = useState({
    todo: "",
    completed: false,
  });

  const fetchTodos = async () => {
    const response = await fetch("/api/todo");
    console.log("called");
    const data = await response.json();
    settodos(data);
  };

  const saveTodo = async () => {
    const response = await fetch("/api/todo", {
      method: "POST",
      body: JSON.stringify(newTodo),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await response.json();
    settodos(data);
  };

  const handleChange = (e) => {
    setnewTodo({
      todo: e.target.value,
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    saveTodo();
    setnewTodo({
      todo: "",
    });
  };

  return (
    <div className={styles.container}>
            
      <Head>
                <title>Create Next App</title>
                
        <meta name="description" content="Generated by create next app" />
                
        <link rel="icon" href="/favicon.ico" />
              
      </Head>
            
      <main>
                <button onClick={fetchTodos}>Get todos</button>
                
        <ul>
                    
          {todos.map((todo) => {
            return (
              <li
                style={{ color: `${todo.completed ? "green" : "red"}` }}
                key={todo.id}
              >
                                {todo.todo}:{todo.completed}.               
              </li>
            );
          })}
                  
        </ul>
              
        <form onSubmit={handleSubmit}>
                    
          <input type="text" onChange={handleChange} value={newTodo.todo} />
                  
        </form>
                
        <ul>
                    {" "}
          {todos.map((todo) => {
            return (
              <li
                style={{ color: `${todo.completed ? "green" : "red"}` }}
                key={todo.id}
              >
                                {todo.todo}:{todo.completed}.               
              </li>
            );
          })}
                  
        </ul>
      </main>
          
    </div>
  );
}
